//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
        public Nullable<System.TimeSpan> appointment_time { get; set; }
        public string examination_result { get; set; }
        public string prescription { get; set; }
        public string advice { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
